# build\_processed\_trades

## Overview

This Python script aggregates portfolio transaction and holdings CSV files for multiple teams, then computes a consolidated `processed_trades.csv` summarizing each completed trade with key metrics.

### Features

* Reads all `Portfolio Transactions - <Team>.csv` and `Holdings - <Team>.csv` files in the `data/` directory
* Drops canceled transactions
* Matches buys/shorts to sells/covers using FIFO
* Calculates per-trade metrics:

  * Entry & exit dates
  * Holding period (days)
  * Quantity and position size
  * Total profit/loss (USD)
  * Percentage return
* Forces exit of any open positions at today’s price from the holdings files
* Outputs `output/processed_trades.csv`

## Requirements

See `requirements.txt` for Python package dependencies.

## Installation

1. Clone the repository
2. `cd` into the project root
3. Install dependencies:

```bash
pip install -r requirements.txt
```

## Usage

1. Ensure your directory structure:

   ```plaintext
   project_root/
   ├── build_processed_trades.py
   ├── data/
   │   ├── Portfolio Transactions - Team A.csv
   │   ├── Portfolio Transactions - Team B.csv
   │   ├── …
   │   ├── Holdings - Team A.csv
   │   ├── Holdings - Team B.csv
   │   └── …
   └── output/        # will be created automatically
   ```

2. Run the script:

```bash
python build_processed_trades.py
```

3. Find the consolidated output here:

```
output/processed_trades.csv
```

## Customization

* If you want a different output location, modify the `OUT_DIR` constant at the top of `build_processed_trades.py`.
* To change the risk‑cutoff or other rules, edit the relevant helper functions—everything is modular and well-commented.

---

*Generated by ChatGPT*
